# Generated by Django 3.0.4 on 2020-03-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='round_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
