# Generated by Django 3.0.4 on 2020-03-06 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200306_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Core-2nd Year', 'Core-2nd Year'), ('Core-1st Year', 'Core-1st Year'), ('Board', 'Board'), ('Judge', 'Judge'), ('Speaker', 'Speaker'), ('Faculty', 'Faculty'), ('Others', 'Others')], max_length=100)),
                ('weightage', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='usertype',
            name='type_of_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Metrix'),
        ),
    ]
