# Generated by Django 3.0.4 on 2020-03-06 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200306_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaging',
            name='team',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='core.TeamInfo'),
            preserve_default=False,
        ),
    ]
