# Generated by Django 3.0.4 on 2020-03-09 20:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationParms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('novelty_slider', models.IntegerField()),
                ('tech_feasability_slider', models.IntegerField()),
                ('work_done_slider', models.IntegerField(default=0)),
                ('impact_slider', models.IntegerField()),
                ('presentation_quality_slider', models.IntegerField()),
                ('bussiness_model_slider', models.IntegerField()),
                ('scalability_slider', models.IntegerField()),
                ('remarks', models.CharField(max_length=300)),
                ('notes', models.CharField(default='Not Filled', max_length=300)),
                ('suggesstions_given', models.CharField(default='Not Filled', max_length=300)),
                ('evaluator', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.evaluator')),
            ],
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='type_of_user',
        ),
        migrations.AddField(
            model_name='teaminfo',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='category',
            field=models.CharField(choices=[('Core-2nd Year', 'Core-2nd Year'), ('Core-1st Year', 'Core-1st Year'), ('Board', 'Board'), ('Judge', 'Judge')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Metrix',
        ),
    ]
